-- year8 activity expansion: 4 -> 28 active activities.
-- 8 new activities each in Reading, Writing and Mathematics, showing
-- genuine progression beyond the year7 batch (integer operations vs.
-- comparison, two-step equations vs. one-step, angle-sum reasoning vs.
-- classification, mean/median vs. reading a chart, percentage increase vs.
-- discount, combined-event probability vs. single-event likelihood,
-- multi-source synthesis vs. two-source comparison, theme/symbolism vs.
-- literal inference) rather than the same mechanics relabelled.
-- curriculum_map reuses the fixed phrasing established by this stage's 4
-- existing rows per subject. skill_key left null (pathways stop at year6).
-- Duplicate-title-checked against live titles before insert; no collisions.

INSERT INTO public.weekly_activities
  (id, stage_key, area, title, activity_template, why_it_matters, easier_variant, stretch_variant, curriculum_map, source_basis, content_version, sort_order, active, resource_keys)
VALUES
  (
    'year8-theme',
    'year8',
    'Reading',
    'What''s this really about?',
    'After reading a short story or article, ask {name} to name the underlying theme or message, separate from just retelling the plot or topic.',
    'Identifying theme requires reading beyond the literal events to what a text is really exploring.',
    'Offer two possible themes to choose between.',
    'Ask {name} to find one specific detail that supports the theme.',
    '{"Victoria": "Year 8 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 8 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 8 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 8 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    113,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-symbolism',
    'year8',
    'Reading',
    'What does this stand for?',
    'Find one symbol or piece of figurative language in a text and ask {name} what it might represent beyond its literal meaning.',
    'Recognising symbolism is a step toward deeper literary analysis beyond surface-level reading.',
    'Explain the symbol yourself and ask {name} whether they agree.',
    'Ask {name} to find a second symbol in the same text.',
    '{"Victoria": "Year 8 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 8 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 8 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 8 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    114,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-three-sources',
    'year8',
    'Reading',
    'Three sources, one topic',
    'Give {name} three short sources on the same topic and ask them to note one thing all three agree on and one place they disagree.',
    'Comparing multiple sources builds the synthesis skill needed for research and informed opinion-forming.',
    'Use just two sources instead of three.',
    'Ask {name} which source seems most reliable, and why.',
    '{"Victoria": "Year 8 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 8 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 8 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 8 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    115,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-spot-the-slant',
    'year8',
    'Reading',
    'Spot the slant',
    'In an opinion piece or persuasive text, ask {name} to find language choices that reveal the author''s stance on the topic.',
    'Identifying bias through language choice is a core critical reading skill at this level.',
    'Point out one loaded word yourself and ask what it reveals.',
    'Ask how the piece might be rewritten more neutrally.',
    '{"Victoria": "Year 8 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 8 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 8 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 8 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    116,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-persuasive-technique',
    'year8',
    'Reading',
    'Name the technique',
    'In an ad or opinion piece, ask {name} to identify a persuasive technique being used, such as an appeal to emotion, a statistic, or an expert opinion.',
    'Naming persuasive techniques builds resistance to being persuaded without noticing how.',
    'Offer a short list of techniques to choose from.',
    'Ask {name} to find a second technique in the same piece.',
    '{"Victoria": "Year 8 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 8 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 8 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 8 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    117,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-25-word-summary',
    'year8',
    'Reading',
    'The 25-word summary',
    'After reading a longer or denser article, challenge {name} to summarise it in exactly 25 words, forcing hard choices about what matters most.',
    'A strict word limit forces genuine prioritisation, which is a more demanding skill than an open-ended summary.',
    'Allow a 50-word limit instead.',
    'Try cutting the summary down to 15 words.',
    '{"Victoria": "Year 8 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 8 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 8 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 8 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    118,
    true,
    ARRAY['supporting-reading-writing-in-high-school']::text[]
  ),
  (
    'year8-prove-the-inference',
    'year8',
    'Reading',
    'Prove your inference',
    'Ask {name} to make an inference about a character or situation, then point to the specific piece of text evidence that supports it.',
    'Backing an inference with evidence is what separates a guess from genuine analytical reading.',
    'Offer the evidence and ask what inference it supports.',
    'Find a second piece of evidence for the same inference.',
    '{"Victoria": "Year 8 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 8 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 8 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 8 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    119,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-connotation',
    'year8',
    'Reading',
    'Same meaning, different feeling',
    'Compare two words with a similar literal meaning but a different feeling, such as “slender” and “skinny”, and discuss the effect of each.',
    'Noticing connotation, not just definition, is essential to understanding how word choice shapes meaning.',
    'Explain the difference yourself and ask {name} which they''d use and when.',
    'Find a third word with yet another shade of the same meaning.',
    '{"Victoria": "Year 8 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 8 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 8 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 8 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    120,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-state-position',
    'year8',
    'Writing',
    'State your position',
    'Before writing a persuasive piece, ask {name} to write one clear sentence stating their position on the topic.',
    'A clear thesis statement gives the whole piece direction and makes it easier to check every paragraph supports it.',
    'Offer two position statements and ask {name} to pick and adjust one.',
    'Ask {name} to explain why they chose that exact wording.',
    '{"Victoria": "Year 8 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 8 English \u2014 creating texts and language features", "New Zealand": "Year 8 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 8 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    121,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-counter-argument',
    'year8',
    'Writing',
    'What would the other side say?',
    'Ask {name} to write one sentence acknowledging an opposing view before responding to it in their persuasive writing.',
    'Addressing a counter-argument makes persuasive writing more convincing and shows genuine engagement with the topic.',
    'Suggest the counter-argument and ask {name} to respond to it.',
    'Ask {name} to find the strongest possible opposing point, not just an easy one.',
    '{"Victoria": "Year 8 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 8 English \u2014 creating texts and language features", "New Zealand": "Year 8 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 8 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    122,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-formal-register',
    'year8',
    'Writing',
    'Dial the tone up or down',
    'Take an informal sentence {name} has written and ask them to rewrite it in a more formal register, or the reverse.',
    'Adjusting register for context is a genuine, transferable writing skill increasingly expected at this level.',
    'Rewrite just one word or phrase rather than the whole sentence.',
    'Try the same sentence in a third, different register.',
    '{"Victoria": "Year 8 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 8 English \u2014 creating texts and language features", "New Zealand": "Year 8 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 8 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    123,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-show-dont-tell',
    'year8',
    'Writing',
    'Show it, don''t just say it',
    'Take a “telling” sentence such as “she was angry” and ask {name} to rewrite it to show the feeling through action or detail instead.',
    'Showing rather than telling makes writing more vivid and is a genuine craft skill worth practising deliberately.',
    'Offer one detail as a starting point to build the sentence around.',
    'Try showing a second, different feeling the same way.',
    '{"Victoria": "Year 8 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 8 English \u2014 creating texts and language features", "New Zealand": "Year 8 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 8 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    124,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-short-for-emphasis',
    'year8',
    'Writing',
    'Short and sharp',
    'In a paragraph of longer sentences, ask {name} to add one deliberately short sentence for emphasis and discuss the effect.',
    'Varying sentence length on purpose is a sentence-craft skill that goes beyond simply avoiding repetition.',
    'Suggest where the short sentence could go.',
    'Try moving the short sentence to a different spot and compare the effect.',
    '{"Victoria": "Year 8 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 8 English \u2014 creating texts and language features", "New Zealand": "Year 8 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 8 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    125,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-cut-the-clutter',
    'year8',
    'Writing',
    'Cut the clutter',
    'Take a paragraph of {name}''s own writing and challenge them to remove as many unnecessary words as possible without losing the meaning.',
    'Editing for conciseness is a distinct skill from editing for correctness, and it sharpens writing considerably.',
    'Find and cut just one unnecessary phrase together.',
    'Set a target: cut the word count by 20% without losing meaning.',
    '{"Victoria": "Year 8 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 8 English \u2014 creating texts and language features", "New Zealand": "Year 8 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 8 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    126,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-quote-properly',
    'year8',
    'Writing',
    'Quote it properly',
    'Ask {name} to integrate a short quote from a source into their own sentence, with a clear attribution such as “according to...”.',
    'Integrating and attributing quotes correctly is a foundational academic writing skill.',
    'Provide the attribution phrase and let {name} add the quote.',
    'Ask {name} to add one sentence explaining why the quote matters.',
    '{"Victoria": "Year 8 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 8 English \u2014 creating texts and language features", "New Zealand": "Year 8 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 8 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    127,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-plan-whole-piece',
    'year8',
    'Writing',
    'Plan the whole piece',
    'Before a longer piece of writing, ask {name} to plan an introduction, two or three body sections and a conclusion in a few quick notes.',
    'Planning the full structure before writing reduces the common problem of a longer piece losing direction partway through.',
    'Plan just the introduction and conclusion first.',
    'Add one planned piece of evidence for each body section.',
    '{"Victoria": "Year 8 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 8 English \u2014 creating texts and language features", "New Zealand": "Year 8 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 8 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    128,
    true,
    ARRAY['supporting-reading-writing-in-high-school']::text[]
  ),
  (
    'year8-integer-operations',
    'year8',
    'Mathematics',
    'Add and subtract below zero',
    'Use a real context, such as temperature change or a bank balance, and ask {name} to add and subtract across zero, not just compare values.',
    'Operating with negative numbers, not just comparing them, is the next real step in integer understanding.',
    'Stick to addition only, without crossing into subtraction.',
    'Add a third step to the same real-context calculation.',
    '{"Victoria": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 8 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    129,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-two-step-equation',
    'year8',
    'Mathematics',
    'Two-step mystery number',
    'Give {name} a two-step equation, such as 2x − 5 = 9, and ask them to solve it by undoing the operations in the correct order.',
    'Two-step equations require sequencing the undo-steps correctly, a genuine step up from one-step equations.',
    'Work through the first step together, then let {name} finish it.',
    'Ask {name} to write their own two-step equation for someone else to solve.',
    '{"Victoria": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 8 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    130,
    true,
    ARRAY['maths-explanation-over-reteaching']::text[]
  ),
  (
    'year8-angle-sum',
    'year8',
    'Mathematics',
    'Angles in a shape',
    'Give {name} a triangle or quadrilateral with one or two angles missing and ask them to find the missing angle using the fact that the angles add to a known total.',
    'Using angle-sum facts to find missing angles is a genuine geometric reasoning skill, not just measurement.',
    'Use a triangle with only one missing angle.',
    'Try a quadrilateral with two missing angles.',
    '{"Victoria": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 8 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    131,
    true,
    ARRAY['maths-explanation-over-reteaching']::text[]
  ),
  (
    'year8-volume',
    'year8',
    'Mathematics',
    'How much does it hold?',
    'Measure a real rectangular container — a box, a drawer, a fish tank — and ask {name} to calculate its volume.',
    'Calculating volume from real measurements connects a formula to something genuinely tangible.',
    'Provide the measurements already taken.',
    'Ask {name} to estimate before calculating, then compare.',
    '{"Victoria": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 8 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    132,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-combined-probability',
    'year8',
    'Mathematics',
    'What are the chances of both?',
    'Using two simple independent events, such as two coin flips or two dice rolls, ask {name} to reason informally about the chance of both happening.',
    'Reasoning about combined events is a genuine step up from single-event probability.',
    'List all the possible outcomes together before reasoning about chance.',
    'Ask {name} to estimate a rough fraction or percentage for the combined chance.',
    '{"Victoria": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 8 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    133,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-mean-median',
    'year8',
    'Mathematics',
    'Find the middle and the average',
    'Use a small real data set, such as a week of daily step counts, and ask {name} to find both the mean and the median, then discuss what each tells you.',
    'Comparing mean and median builds a genuine understanding of what each measure actually represents.',
    'Calculate just the mean first, then add the median.',
    'Ask {name} how one unusually high or low value affects each measure differently.',
    '{"Victoria": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 8 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    134,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-percentage-change',
    'year8',
    'Mathematics',
    'Price after the rise',
    'Use a real or realistic example of a price rise or population growth and ask {name} to calculate the new value after a percentage increase.',
    'Percentage increase, not just discount, is a common and useful real-world application of percentage reasoning.',
    'Use a simple round percentage like 10% or 20%.',
    'Ask {name} to work out what percentage increase occurred, given the before and after values.',
    '{"Victoria": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 8 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    135,
    true,
    ARRAY[]::text[]
  ),
  (
    'year8-scale-drawing',
    'year8',
    'Mathematics',
    'Read the scale',
    'Using a map or scale drawing, ask {name} to use the given scale to work out a real-world distance or size.',
    'Interpreting scale is a practical application of ratio reasoning with genuine everyday use.',
    'Use a simple whole-number scale such as 1cm = 1km.',
    'Ask {name} to work backward from a real distance to a scale-drawing length.',
    '{"Victoria": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 8 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 8 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    136,
    true,
    ARRAY[]::text[]
  )
;
