-- m24 (24-29 months) activity expansion: 4 -> 28 active activities.
-- Areas match the m18 area taxonomy this stage inherits from (Communication,
-- Thinking, Movement, Fine motor, Independence, Play, Early literacy,
-- Early numeracy, Connection). Guardrail-checked against
-- development_stages.content_guardrails.forbidden_terms for m24; no violations.
-- skill_key left null (skill_pathways coverage starts at m36). Duplicate-checked
-- against live titles before insert.

INSERT INTO public.weekly_activities
  (id, stage_key, area, title, activity_template, why_it_matters, easier_variant, stretch_variant, curriculum_map, source_basis, content_version, sort_order, active, resource_keys)
VALUES
  (
    'm24-choice-question',
    'm24',
    'Communication',
    'This one or that one?',
    'Offer a simple two-choice question (“apple or banana?”) during a real moment like snack time, and wait for {name} to answer in any way — a word, a point, or a reach.',
    'Answering a choice question builds requesting language and puts two-word understanding into real use.',
    'Hold up both options without words and let {name} choose by reaching.',
    'Offer a three-item choice instead of two.',
    '{"Victoria": "VEYLDF Outcome 5 — children are effective communicators", "Queensland": "EYLF V2.0 Outcome 5 — children are effective communicators", "New Zealand": "Te Whāriki — Mana Reo / Communication", "New South Wales": "EYLF V2.0 Outcome 5 — children are effective communicators"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    41,
    true,
    ARRAY['word-explosion-what-to-do']::text[]
  ),
  (
    'm24-one-step-no-gesture',
    'm24',
    'Communication',
    'One instruction, no pointing',
    'Give one simple instruction without any pointing or gesture, such as “bring me your shoe”, using an object {name} already knows well.',
    'Following an instruction from words alone, with no visual cue, is a genuine test of understanding at this age.',
    'Add a small pointing gesture alongside the words.',
    'Try the instruction using an object that isn''t currently visible.',
    '{"Victoria": "VEYLDF Outcome 5 — children are effective communicators", "Queensland": "EYLF V2.0 Outcome 5 — children are effective communicators", "New Zealand": "Te Whāriki — Mana Reo / Communication", "New South Wales": "EYLF V2.0 Outcome 5 — children are effective communicators"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    42,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-photo-naming',
    'm24',
    'Communication',
    'Who''s in the photo?',
    'Look at a few family photos together and ask {name} to name who they see, or name them yourself and pause for {name} to repeat or point.',
    'Naming familiar people in photos builds vocabulary and connects words to people {name} cares about.',
    'Point to each person yourself and say the name.',
    'Ask a simple question about the photo, such as “what is he doing?”',
    '{"Victoria": "VEYLDF Outcome 5 — children are effective communicators", "Queensland": "EYLF V2.0 Outcome 5 — children are effective communicators", "New Zealand": "Te Whāriki — Mana Reo / Communication", "New South Wales": "EYLF V2.0 Outcome 5 — children are effective communicators"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    43,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-two-piece-puzzle',
    'm24',
    'Thinking',
    'Where does this piece go?',
    'Offer a simple two- or three-piece puzzle or shape sorter and let {name} work out where each piece goes, without giving the answer straight away.',
    'Matching shapes through trial and adjustment builds early problem-solving.',
    'Turn a piece to the right position and let {name} push it in.',
    'Try a puzzle with one or two more pieces.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    44,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-copy-the-sequence',
    'm24',
    'Thinking',
    'Copy my two steps',
    'Do a short two-step action with a toy, such as stacking one block then adding a second, and invite {name} to copy exactly what you did.',
    'Copying a short sequence builds memory and the ability to plan more than one step ahead.',
    'Do the sequence together, hand over hand.',
    'Add a third step to the sequence.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    45,
    true,
    ARRAY['early-pretend-play-onset']::text[]
  ),
  (
    'm24-climb-on-off',
    'm24',
    'Movement',
    'Climb up, climb down safely',
    'In a safe, supervised space, let {name} practise climbing onto and safely getting down from a low, stable surface such as a step or a cushion.',
    'Climbing and safely dismounting builds balance, strength and body awareness.',
    'Support {name}''s hand or hip while they climb.',
    'Add a second low step to climb across.',
    '{"Victoria": "VEYLDF Outcome 3 — children have a strong sense of wellbeing", "Queensland": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing", "New Zealand": "Te Whāriki — Mana Atua / Wellbeing", "New South Wales": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    46,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-throw-with-aim',
    'm24',
    'Movement',
    'Throw toward a target',
    'Roll or throw a soft ball toward a simple target, such as a box or laundry basket, a short distance away.',
    'Throwing with a direction in mind builds coordination beyond kicking or dropping.',
    'Move the target very close and make it large.',
    'Move the target a little further away.',
    '{"Victoria": "VEYLDF Outcome 3 — children have a strong sense of wellbeing", "Queensland": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing", "New Zealand": "Te Whāriki — Mana Atua / Wellbeing", "New South Wales": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    47,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-turn-pages',
    'm24',
    'Fine motor',
    'Turn the pages yourself',
    'Let {name} hold a sturdy board book and turn the pages themselves, even if more than one page turns at once.',
    'Turning pages one at a time is a genuine fine motor skill this age is actively building.',
    'Help start the page lift, then let {name} finish the turn.',
    'Use a book with thinner paper pages instead of board pages.',
    '{"Victoria": "VEYLDF Outcome 3 — children have a strong sense of wellbeing", "Queensland": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing", "New Zealand": "Te Whāriki — Mana Atua / Wellbeing", "New South Wales": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    48,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-pour-between-cups',
    'm24',
    'Fine motor',
    'Pour from cup to cup',
    'With water in the bath, or dry rice or pasta at the table, let {name} practise pouring from one cup into another.',
    'Pouring builds hand control and an early sense of quantity, and it''s genuinely absorbing at this age.',
    'Use two cups with wide openings to make pouring easier.',
    'Add a third, smaller cup to pour into.',
    '{"Victoria": "VEYLDF Outcome 3 — children have a strong sense of wellbeing", "Queensland": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing", "New Zealand": "Te Whāriki — Mana Atua / Wellbeing", "New South Wales": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    49,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-first-scribbles',
    'm24',
    'Fine motor',
    'Free scribble time',
    'Offer chunky crayons and paper and let {name} scribble freely, without asking them to draw anything specific.',
    'Early scribbling builds the hand strength and control that later supports drawing and writing.',
    'Scribble alongside {name} on your own piece of paper.',
    'Offer a slightly larger sheet of paper to fill.',
    '{"Victoria": "VEYLDF Outcome 3 — children have a strong sense of wellbeing", "Queensland": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing", "New Zealand": "Te Whāriki — Mana Atua / Wellbeing", "New South Wales": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    50,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-try-a-piece-of-clothing',
    'm24',
    'Independence',
    'Try one dressing step',
    'At dressing time, let {name} attempt one simple step themselves, such as pulling on a hat or pushing a foot into a shoe, before helping.',
    'Attempting one dressing step builds the confidence and coordination independence depends on.',
    'Do the step together, guiding {name}''s hands.',
    'Offer two steps in a row before helping.',
    '{"Victoria": "VEYLDF Outcome 1 — children have a strong sense of identity", "Queensland": "EYLF V2.0 Outcome 1 — children have a strong sense of identity", "New Zealand": "Te Whāriki — Mana Whenua / Belonging", "New South Wales": "EYLF V2.0 Outcome 1 — children have a strong sense of identity"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    51,
    true,
    ARRAY['me-do-it-toddler-independence']::text[]
  ),
  (
    'm24-tidy-one-bin',
    'm24',
    'Independence',
    'Put the blocks in the bin',
    'Ask {name} to help put toys into one bin or basket at tidy-up time, using a simple, specific request like “put the blocks in”.',
    'A specific, achievable request builds real participation, unlike a vague “tidy up”.',
    'Hand {name} one toy at a time to place in the bin.',
    'Ask {name} to sort two toy types into two separate bins.',
    '{"Victoria": "VEYLDF Outcome 1 — children have a strong sense of identity", "Queensland": "EYLF V2.0 Outcome 1 — children have a strong sense of identity", "New Zealand": "Te Whāriki — Mana Whenua / Belonging", "New South Wales": "EYLF V2.0 Outcome 1 — children have a strong sense of identity"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    52,
    true,
    ARRAY['me-do-it-toddler-independence']::text[]
  ),
  (
    'm24-spoon-self-feed',
    'm24',
    'Independence',
    'Spoon it yourself',
    'Let {name} use a spoon to feed themselves part of a meal, even if it''s slow or messy.',
    'Self-feeding with a spoon builds fine motor control and mealtime independence.',
    'Load the spoon for {name} and let them lift and eat it.',
    'Let {name} load the spoon themselves for part of the meal.',
    '{"Victoria": "VEYLDF Outcome 1 — children have a strong sense of identity", "Queensland": "EYLF V2.0 Outcome 1 — children have a strong sense of identity", "New Zealand": "Te Whāriki — Mana Whenua / Belonging", "New South Wales": "EYLF V2.0 Outcome 1 — children have a strong sense of identity"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    53,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-play-alongside',
    'm24',
    'Play',
    'Play side by side',
    'Set {name} up with similar toys next to another child or sibling, playing near each other without needing to share the same toy.',
    'Playing alongside another child, without pressure to interact constantly, is a genuine and comfortable form of social play at this age.',
    'Sit nearby yourself if no other child is available.',
    'Offer one toy that could be used by both children together, like a large ball.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    54,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-copy-me-game',
    'm24',
    'Play',
    'Copy-me game',
    'Play a simple copying game — you do an action like clapping or stomping, and {name} copies it, then swap so {name} leads and you copy them.',
    'Copying games build turn-taking and body awareness in an easy, playful way.',
    'Keep the actions very simple and repeat the same one a few times.',
    'Take turns adding a new action to copy each round.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    55,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-messy-sensory-play',
    'm24',
    'Play',
    'Messy tray play',
    'Offer a simple tactile play experience, such as dry rice in a tub, shaving cream on a tray, or mud outside, with tools like cups and spoons to explore it.',
    'Open messy play builds sensory tolerance and gives plenty to talk about together.',
    'Start with a small amount in a shallow tray.',
    'Add tools like a sieve or funnel to scoop and pour with.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    56,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-join-the-refrain',
    'm24',
    'Early literacy',
    'Join in the repeated line',
    'In a favourite, familiar book with a repeated phrase, pause before the repeated part and let {name} fill it in or join in.',
    'Joining in with a repeated refrain builds memory for story language and a sense of book rhythm.',
    'Say the refrain together at the same time.',
    'Pause a beat longer to see if {name} starts it without you.',
    '{"Victoria": "VEYLDF Outcome 5 — children are effective communicators", "Queensland": "EYLF V2.0 Outcome 5 — children are effective communicators", "New Zealand": "Te Whāriki — Mana Reo / Communication", "New South Wales": "EYLF V2.0 Outcome 5 — children are effective communicators"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    57,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-spot-your-name',
    'm24',
    'Early literacy',
    'Spot your own name',
    'Write {name}''s name on a piece of paper and point it out on other things around the house, such as a labelled drawer or bag.',
    'Recognising their own name written down is often a toddler''s first real piece of print awareness.',
    'Just point out the name and say it, without expecting a response.',
    'Ask {name} to find their name among two or three different labels.',
    '{"Victoria": "VEYLDF Outcome 5 — children are effective communicators", "Queensland": "EYLF V2.0 Outcome 5 — children are effective communicators", "New Zealand": "Te Whāriki — Mana Reo / Communication", "New South Wales": "EYLF V2.0 Outcome 5 — children are effective communicators"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    58,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-read-to-a-toy',
    'm24',
    'Early literacy',
    'Read the book to teddy',
    'Give {name} a board book and a stuffed toy and encourage them to “read” the story to the toy in their own words or babble.',
    'Pretending to read to someone else shows {name} understands what books are for, well before they can read the words themselves.',
    'Model reading to the toy first, then hand the book over.',
    'Ask {name} what the toy thought of the story.',
    '{"Victoria": "VEYLDF Outcome 5 — children are effective communicators", "Queensland": "EYLF V2.0 Outcome 5 — children are effective communicators", "New Zealand": "Te Whāriki — Mana Reo / Communication", "New South Wales": "EYLF V2.0 Outcome 5 — children are effective communicators"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    59,
    true,
    ARRAY['early-pretend-play-onset']::text[]
  ),
  (
    'm24-match-the-same',
    'm24',
    'Early numeracy',
    'Find the matching pair',
    'Offer a small group of matching pairs, such as two identical socks or two identical toy cars, and ask {name} to find the ones that match.',
    'Matching identical objects is genuine early maths thinking, well before formal counting.',
    'Start with just one pair among a couple of clearly different objects.',
    'Add a third matching pair to find.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    60,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-fill-and-empty',
    'm24',
    'Early numeracy',
    'Fill it up, tip it out',
    'Give {name} a container and some small safe objects to fill it up and tip it out again, noticing together when it''s “full” or “empty”.',
    'Filling and emptying builds an early, hands-on sense of quantity.',
    'Use larger, easier-to-handle objects.',
    'Compare two containers and notice which holds more.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    61,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-big-and-small',
    'm24',
    'Early numeracy',
    'Find the big one',
    'Point out big and small versions of the same everyday object, such as a big spoon and a small spoon, and ask {name} to find the big one or the small one.',
    'Comparing size is one of the earliest maths ideas toddlers build, well before number words matter much.',
    'Show two very different-sized objects side by side.',
    'Line up three objects and ask which is biggest.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    62,
    true,
    ARRAY[]::text[]
  ),
  (
    'm24-notice-a-feeling',
    'm24',
    'Connection',
    'Notice how someone feels',
    'Notice a clear feeling in someone nearby — a sibling crying, a character in a book looking sad — and name it simply: “he''s sad”.',
    'Naming feelings in others, even briefly, builds the beginning of empathy and emotional vocabulary.',
    'Just name the feeling yourself without asking {name} to respond.',
    'Ask {name} what might help the person feel better.',
    '{"Victoria": "VEYLDF Outcome 2 — children are connected with and contribute to their world", "Queensland": "EYLF V2.0 Outcome 2 — children are connected with and contribute to their world", "New Zealand": "Te Whāriki — Mana Tangata / Contribution", "New South Wales": "EYLF V2.0 Outcome 2 — children are connected with and contribute to their world"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    63,
    true,
    ARRAY['toddler-tantrums-before-three']::text[]
  ),
  (
    'm24-roll-it-back',
    'm24',
    'Connection',
    'Roll it back and forth',
    'Sit facing {name} and roll a ball back and forth, taking clear turns and narrating “your turn... my turn”.',
    'A simple back-and-forth game builds turn-taking in the easiest, most physical way possible at this age.',
    'Sit closer together so the ball travels a shorter distance.',
    'Add a second person to the circle so turns rotate further.',
    '{"Victoria": "VEYLDF Outcome 2 — children are connected with and contribute to their world", "Queensland": "EYLF V2.0 Outcome 2 — children are connected with and contribute to their world", "New Zealand": "Te Whāriki — Mana Tangata / Contribution", "New South Wales": "EYLF V2.0 Outcome 2 — children are connected with and contribute to their world"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    64,
    true,
    ARRAY[]::text[]
  )
;
