-- year7 activity expansion: 4 -> 28 active activities.
-- 8 new activities each in Reading, Writing and Mathematics, spanning
-- genuinely distinct sub-skills per the target-diversity standard (reading:
-- inference, summarising, text structure, morphology, word choice, source
-- comparison, fluency/expression, purpose & audience; writing: topic
-- sentences, sentence combining, planning, audience, evidence, cohesion,
-- structural revision, purpose; maths: negative numbers, angles, composite
-- area, probability, data interpretation, percentage, equations, unit
-- conversion). curriculum_map reuses the exact fixed phrasing already
-- established by this stage's 4 existing rows per subject (not fabricated
-- per-activity — matches the existing convention of one curriculum_map per
-- subject/stage). skill_key left null (skill_pathways coverage stops at
-- year6). Duplicate-title-checked against live titles before insert (1
-- collision found and renamed).

INSERT INTO public.weekly_activities
  (id, stage_key, area, title, activity_template, why_it_matters, easier_variant, stretch_variant, curriculum_map, source_basis, content_version, sort_order, active, resource_keys)
VALUES
  (
    'year7-infer',
    'year7',
    'Reading',
    'Read between the lines',
    'Choose a passage where a character''s feeling is shown through action or dialogue rather than stated directly. Ask {name} to name the feeling and point to what gave it away.',
    'Inference — reading what isn''t directly stated — is a key comprehension skill at this level, beyond literal recall.',
    'Point out the clue yourself first, then ask what feeling it suggests.',
    'Ask {name} to find a second, subtler clue in the same passage.',
    '{"Victoria": "Year 7 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 7 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 7 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 7 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    89,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-summarise',
    'year7',
    'Reading',
    'One paragraph, the whole article',
    'After reading a short article, ask {name} to summarise it in three or four sentences, including only the main points.',
    'Summarising forces a reader to separate main ideas from supporting detail, a genuinely different skill from recall.',
    'Ask for just one sentence capturing the single main idea.',
    'Limit the summary to a strict word count, such as 30 words.',
    '{"Victoria": "Year 7 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 7 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 7 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 7 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    90,
    true,
    ARRAY['supporting-reading-writing-in-high-school']::text[]
  ),
  (
    'year7-text-structure',
    'year7',
    'Reading',
    'Spot the structure',
    'Look at how a text is organised — chronological, problem-and-solution, compare-and-contrast — and ask {name} to name the structure and why it might suit this content.',
    'Noticing structure helps a reader predict where information will appear and follow an argument more easily.',
    'Offer two structure options to choose between.',
    'Ask how the text might read differently with a different structure.',
    '{"Victoria": "Year 7 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 7 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 7 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 7 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    91,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-word-parts',
    'year7',
    'Reading',
    'Guess it from the parts',
    'When {name} hits an unfamiliar word, ask them to guess its meaning from prefixes, suffixes or context before looking it up.',
    'Using word parts and context to work out meaning is faster and more transferable than reaching for a dictionary every time.',
    'Point out a familiar word part inside the unfamiliar word as a starting clue.',
    'Ask {name} to think of another word that shares the same root or prefix.',
    '{"Victoria": "Year 7 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 7 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 7 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 7 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    92,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-word-choice',
    'year7',
    'Reading',
    'Why this word, not another?',
    'Find one deliberately chosen word in a text and ask {name} what a more neutral or ordinary word would have been, and what changes with the author''s choice.',
    'Noticing precise word choice is a step toward analysing how authors create effect, not just what they say.',
    'Offer the neutral alternative yourself and ask what''s different about it.',
    'Find a second example of deliberate word choice in the same text.',
    '{"Victoria": "Year 7 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 7 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 7 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 7 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    93,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-compare-framing',
    'year7',
    'Reading',
    'Same story, different angle',
    'Find two short reports of the same real event and ask {name} to spot one specific word or detail included in one but left out of the other, and what effect that has.',
    'Noticing what''s included or left out is a concrete, checkable way into recognising bias in reporting.',
    'Point out one clear difference yourself and ask what effect it has.',
    'Ask which source {name} would trust more on this topic, and why.',
    '{"Victoria": "Year 7 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 7 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 7 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 7 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    94,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-read-with-expression',
    'year7',
    'Reading',
    'Read it like you mean it',
    'Choose a short passage with a clear mood — tense, funny, sad — and ask {name} to read it aloud in a way that matches that mood.',
    'Reading with expression that matches meaning is a fluency skill that continues to matter well past early reading.',
    'Model reading it with expression first, then have {name} try.',
    'Try reading the same passage in a different, contrasting tone and discuss what changes.',
    '{"Victoria": "Year 7 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 7 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 7 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 7 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    95,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-purpose-audience',
    'year7',
    'Reading',
    'Who wrote this and why?',
    'Choose a piece of persuasive or promotional writing, such as an ad or opinion piece, and ask {name} who it''s likely written for and what the writer wants the reader to do or think.',
    'Considering a text''s purpose and intended audience is a foundation of critical, questioning reading.',
    'Offer two possible purposes to choose between.',
    'Ask what the writer left out that might weaken their case.',
    '{"Victoria": "Year 7 English \u2014 phonic/word knowledge, fluency and comprehension", "Queensland": "Year 7 English \u2014 reading and viewing, word knowledge and comprehension", "New Zealand": "Year 7 English \u2014 reading, word knowledge and meaning-making", "New South Wales": "Year 7 English \u2014 reading, phonics/word recognition and comprehension"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    96,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-topic-sentence',
    'year7',
    'Writing',
    'One idea per paragraph',
    'Ask {name} to write or find a clear topic sentence for a paragraph, then check that every other sentence in the paragraph actually supports it.',
    'A paragraph organised around one clear idea is easier to follow and easier to write well.',
    'Give the topic sentence and ask {name} to check the paragraph matches it.',
    'Find a sentence that doesn''t belong and decide where it should move to.',
    '{"Victoria": "Year 7 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 7 English \u2014 creating texts and language features", "New Zealand": "Year 7 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 7 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    97,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-sentence-combine',
    'year7',
    'Writing',
    'Smooth out the choppy sentences',
    'Take two or three short, choppy sentences and ask {name} to combine them into one smoother sentence, then compare how it reads.',
    'Combining sentences deliberately builds control over sentence structure beyond just writing longer sentences.',
    'Combine just two sentences using a simple joining word.',
    'Find a second way to combine the same sentences with a different effect.',
    '{"Victoria": "Year 7 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 7 English \u2014 creating texts and language features", "New Zealand": "Year 7 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 7 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    98,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-plan-three-boxes',
    'year7',
    'Writing',
    'Plan in three boxes',
    'Before writing, ask {name} to jot down three quick notes: the opening idea, the main point or two, and the closing idea.',
    'A short plan before writing reduces the common problem of a piece wandering without direction.',
    'Fill in the three boxes together before {name} writes.',
    'Add a fourth box for one specific piece of evidence or example.',
    '{"Victoria": "Year 7 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 7 English \u2014 creating texts and language features", "New Zealand": "Year 7 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 7 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    99,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-two-audiences',
    'year7',
    'Writing',
    'Same idea, two audiences',
    'Ask {name} to write the same short message twice — once for a friend, once for a teacher — and compare the word choices between the two.',
    'Adjusting language for audience is a genuine, transferable writing skill at this level.',
    'Write one version together, then let {name} write the second alone.',
    'Try a third version for a much younger reader.',
    '{"Victoria": "Year 7 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 7 English \u2014 creating texts and language features", "New Zealand": "Year 7 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 7 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    100,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-back-it-up',
    'year7',
    'Writing',
    'Back it up',
    'Ask {name} to write one persuasive sentence, then add a specific fact, example or reason that supports it.',
    'Pairing a claim with real support is the foundation of persuasive and evidence-based writing.',
    'Offer the evidence and ask {name} to write the claim it supports.',
    'Add a second, different piece of supporting evidence.',
    '{"Victoria": "Year 7 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 7 English \u2014 creating texts and language features", "New Zealand": "Year 7 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 7 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    101,
    true,
    ARRAY['supporting-reading-writing-in-high-school']::text[]
  ),
  (
    'year7-linking-words',
    'year7',
    'Writing',
    'Connect the dots',
    'Give {name} two related sentences and ask them to add a linking word or phrase — however, as a result, meanwhile — that shows how the ideas connect.',
    'Linking words make the relationship between ideas explicit, which improves flow and clarity.',
    'Offer a choice of two linking words to pick between.',
    'Try two different linking words and discuss how the meaning shifts.',
    '{"Victoria": "Year 7 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 7 English \u2014 creating texts and language features", "New Zealand": "Year 7 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 7 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    102,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-reorder-for-flow',
    'year7',
    'Writing',
    'Move it around',
    'Take a short piece of {name}''s own writing and ask them to try reordering the sentences or paragraphs for better flow, without fixing any errors.',
    'Revising for structure, separately from correcting mistakes, is a distinct and often-skipped writing skill.',
    'Suggest one specific pair of sentences to try swapping.',
    'Explain out loud why the new order works better.',
    '{"Victoria": "Year 7 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 7 English \u2014 creating texts and language features", "New Zealand": "Year 7 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 7 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    103,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-name-the-purpose',
    'year7',
    'Writing',
    'What''s this piece trying to do?',
    'Before {name} starts writing, ask them to name the purpose in one word — persuade, inform, entertain — and check afterward that the draft actually does that.',
    'Naming a clear purpose up front makes it easier to judge afterward whether a piece succeeded.',
    'Offer the purpose and ask {name} to check the draft matches it.',
    'Ask which single sentence best achieves the stated purpose.',
    '{"Victoria": "Year 7 English \u2014 creating texts, sentence/text structure and vocabulary", "Queensland": "Year 7 English \u2014 creating texts and language features", "New Zealand": "Year 7 English \u2014 creating texts for purpose and audience", "New South Wales": "Year 7 English \u2014 creating written texts and language choices"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    104,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-negative-numbers',
    'year7',
    'Mathematics',
    'Below zero',
    'Use a real context — temperature, a bank balance, elevation below sea level — and ask {name} to compare and order some negative and positive values.',
    'Reasoning with negative numbers in real contexts builds the number sense formal integer operations depend on.',
    'Compare just two values, one clearly higher than the other.',
    'Ask {name} to find the difference between a positive and a negative value.',
    '{"Victoria": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 7 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    105,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-angles-classify',
    'year7',
    'Mathematics',
    'Measure and name',
    'Using a protractor or careful estimation, measure a few real angles around the house and ask {name} to classify each as acute, right or obtuse.',
    'Classifying real angles builds the geometric vocabulary and estimation skill that formal angle work depends on.',
    'Sort angles into just two categories: smaller or larger than a right angle.',
    'Ask {name} to estimate an angle''s size before measuring, then check.',
    '{"Victoria": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 7 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    106,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-composite-area',
    'year7',
    'Mathematics',
    'L-shaped room',
    'Sketch or find an irregular room or garden shape and ask {name} to work out its area by splitting it into two or more simpler rectangles.',
    'Splitting an irregular shape into simpler parts is a genuinely useful problem-solving strategy in measurement.',
    'Provide the split already marked and ask {name} to calculate each part.',
    'Ask {name} to find the perimeter as well as the area.',
    '{"Victoria": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 7 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    107,
    true,
    ARRAY['maths-explanation-over-reteaching']::text[]
  ),
  (
    'year7-likelihood-order',
    'year7',
    'Mathematics',
    'How likely is that?',
    'List a few everyday events and ask {name} to order them from impossible to certain, then discuss which are closest to an even chance.',
    'Ordering events by likelihood builds informal probability reasoning before formal calculation is introduced.',
    'Start with just three very different events to order.',
    'Ask {name} to estimate a rough percentage chance for one event.',
    '{"Victoria": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 7 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    108,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-read-a-chart',
    'year7',
    'Mathematics',
    'Make sense of the numbers',
    'Find a simple real chart or table — sports statistics, weather data — and ask {name} a question that requires comparing or combining values, not just reading one off.',
    'Interpreting real data, not just reading single values, is where genuine data literacy begins.',
    'Ask a question answered by reading a single value from the chart.',
    'Ask {name} to explain a trend or pattern they notice in the data.',
    '{"Victoria": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 7 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    109,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-discount-price',
    'year7',
    'Mathematics',
    'Work out the real price',
    'Use a real or realistic sale price and ask {name} to calculate the discount amount or the final price after a percentage off.',
    'Percentage discounts are one of the most common real-world uses of percentage reasoning.',
    'Use a simple percentage like 10% or 50%.',
    'Add a second discount or a tax on top and ask for the final total.',
    '{"Victoria": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 7 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    110,
    true,
    ARRAY[]::text[]
  ),
  (
    'year7-solve-equation',
    'year7',
    'Mathematics',
    'Solve for the mystery number',
    'Give {name} a simple one- or two-step equation, such as 3x + 2 = 14, and ask them to find the mystery number by undoing each operation in order.',
    'Solving simple equations by undoing operations builds the reasoning that more formal algebra depends on.',
    'Use a one-step equation only.',
    'Ask {name} to check their answer by substituting it back in.',
    '{"Victoria": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 7 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    111,
    true,
    ARRAY['maths-explanation-over-reteaching']::text[]
  ),
  (
    'year7-unit-conversion',
    'year7',
    'Mathematics',
    'Convert and compare',
    'Use two real products with different units — grams and kilograms, millilitres and litres — and ask {name} to convert one so the two can be compared fairly.',
    'Converting between related units is essential for comparing real quantities accurately.',
    'Provide the conversion factor and ask {name} to apply it.',
    'Ask which product is better value once the units match.',
    '{"Victoria": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "Queensland": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New Zealand": "Year 7 Mathematics \u2014 number, algebra and mathematical reasoning", "New South Wales": "Year 7 Mathematics \u2014 number and algebraic thinking"}'::jsonb,
    'Learn Along original activity aligned to school-year curriculum progression',
    'activity-v5.0',
    112,
    true,
    ARRAY[]::text[]
  )
;
