UPDATE public.parent_resources
SET body = 'Balancing, climbing, dancing, copying movements, obstacle paths and animal walks all build coordination and spatial awareness — the sense of where the body is in space that underpins everything from handwriting posture to catching a ball later on. For young children, movement does not need to look like organised sport, and it doesn''t need a coach, a class or specialist equipment. A cushion trail across the lounge room, a chalk line on the driveway, or a game of freeze when the music stops all give the same underlying practice: controlling the body on purpose. Children this age are also building the vestibular and proprioceptive sense that tells them how fast they''re moving and how much force a movement needs, which is why wobbly, tumbling, upside-down play is doing real work even when it looks like nothing more than mucking around. Variety, enjoyment and safe opportunities to move — spread through the day rather than saved for one block of exercise — are what matter most at this age.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'movement-through-play';

UPDATE public.parent_resources
SET body = 'Drawing, peeling stickers, playdough, threading, tongs, child-safe scissors and helping with clothing all develop the hand strength, finger isolation and two-hand coordination that later support handwriting, cutlery use and dressing. Fine-motor development is gradual and highly individual: the small muscles in the hand and wrist are among the last to mature, so a three-year-old''s grip and control will look very different from a five-year-old''s, even with the same amount of practice. Offering varied experiences — squeezing, pinching, twisting, threading, tearing — builds the underlying strength and control that a “correct” pencil grip depends on, rather than the grip itself being something to drill directly. Everyday tasks count just as much as toys: doing up buttons, peeling a mandarin, or carrying a full cup all ask the hand to do real work. Let control improve gradually through genuine use, rather than insisting on one perfect grip or posture before a child''s hand is ready for it.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'fine-motor-through-play';

UPDATE public.parent_resources
SET body = 'Take two or three short related sentences and explore different ways to combine them — this is one of the more reliable ways to build a child''s control over sentence structure, because it works with ideas they already have rather than asking them to invent new content. Discuss which idea should carry the emphasis: joining two sentences with “and” treats them as equally important, while “because”, “although” or “when” tells the reader how the ideas relate to each other. Try more than one combination of the same two sentences and compare how the meaning shifts with each — often there''s more than one reasonable answer, and talking through why one reads better than another is where the real learning happens. The purpose is flexible sentence control, not simply making sentences longer for its own sake; a well-placed short sentence next to a combined one can be more effective than combining everything in sight. Reading the new sentence aloud afterwards is a quick, reliable check for whether it actually makes sense.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'sentence-combining-at-home';

UPDATE public.parent_resources
SET body = 'Percent means “per hundred” — every percentage is really a fraction with a denominator of 100, which is why connecting it back to fractions and decimals matters more than memorising a separate set of rules. Start with benchmarks a child can picture without calculating: 50% is half, 25% is a quarter, 10% is a tenth, 1% is a hundredth. From there, most percentage problems become a matter of combining benchmarks — 30% is 10% three times over, 60% is a bit more than half. A 100-grid or a real quantity (a jar of 100 marbles, a $100 note) makes the “per hundred” idea concrete rather than abstract. Once benchmarks are solid, connect the same value across percent, decimal and fraction forms — 25%, 0.25 and ¼ are the same number written three ways, and being able to move between them is more useful than any single procedure. When calculating a percentage change, keep the change amount and the final value clearly separate: a 20% discount on a $50 item is a $10 reduction, giving a final price of $40, not a final price of $20. This is also where percentage points and percent change get confused — a rate moving from 10% to 15% is a 5 percentage point increase, but a 50% relative increase, and the two describe genuinely different things.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'percentages-at-home';

UPDATE public.parent_resources
SET body = 'Fractions describe numbers — specific points and quantities — not just shaded pizza slices, and treating them only as “parts of a shape” is one of the most common reasons fraction understanding stalls in upper primary. The two ideas that matter most are that the whole has to stay the same when you''re comparing fractions, and that fractions can be split into equal partitions in more than one way. A number line is one of the most useful tools here, because it shows a fraction as an actual quantity sitting between two whole numbers, rather than just a slice of a single divided shape — which is also why relying only on circular food models (pizzas, pies) can quietly reinforce the idea that fractions are always about splitting one object, rather than about a relationship between numbers. Comparing fractions to useful benchmarks — one half, one whole, a bit more or less than either — builds a working sense of size that a procedure alone doesn''t give. When formal procedures do arrive, such as finding a common denominator or cross-multiplying to compare fractions, keep asking what the numerator, denominator and operation actually mean for the quantity involved; a procedure used without that anchor is easy to apply to the wrong problem, and a genuinely bigger denominator does not automatically make a bigger fraction — it depends entirely on the numerator too.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'fractions-at-home';

UPDATE public.parent_resources
SET body = 'Ratio compares two quantities multiplicatively — for every 2 of this, there are 3 of that — while a rate compares two quantities measured in different units, such as kilometres per hour or dollars per kilogram. Both ideas show up constantly in everyday contexts: recipes (double the ingredients, keep the proportions the same), map scales (1cm represents 1km), unit prices (which size jar is actually cheaper per gram) and speed. Building a table of equivalent pairs is one of the more reliable ways to make the relationship visible — 2:3, 4:6, 6:9 — and then asking what multiplying factor connects each pair, rather than what''s been added, is the key move. This is where ratio reasoning most often goes wrong: scaling a ratio means multiplying both quantities by the same factor, not adding the same amount to both, because adding a constant changes the relationship between them even though it feels like “keeping things fair”. Keeping units attached to every number — not just “3” but “3 cups of flour” — also prevents a common source of errors when a problem involves more than one kind of quantity. Finding a unit rate (the amount for just one of something) is often the fastest way to compare two options directly, and it''s worth reaching for before any formal cross-multiplication procedure, which works better once the underlying relationship is already understood.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'ratio-and-rate-at-home';

UPDATE public.parent_resources
SET body = 'Decimals make sense when each digit keeps its place-value meaning: in 3.47, the 4 is worth four tenths and the 7 is worth seven hundredths, not simply “the numbers after the dot”. A number line is one of the clearest ways to show this, because it places a decimal as an actual point between two whole numbers rather than as a string of digits to be compared left to right. Money and measurement are also useful everyday anchors — $3.47 or 3.47 metres both carry the same place-value structure, which is why connecting decimal notation to real quantities tends to stick better than working with bare numbers alone. Where decimals commonly go wrong is when children compare them the way they''d compare whole numbers — assuming 3.9 is smaller than 3.15 because “15 is bigger than 9” — when in fact the first decimal place already settles it. Connecting tenths and hundredths back to the equivalent fractions (0.4 = 4/10, 0.25 = 25/100) reinforces that decimals and fractions are two notations for the same underlying idea, not two separate topics. Estimating before calculating — is this answer roughly 3, or roughly 30? — is one of the simplest and most effective checks for whether a decimal calculation has gone genuinely wrong, especially once a misplaced decimal point can change an answer by a factor of ten.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'decimals-at-home';

UPDATE public.parent_resources
SET body = 'Multiplication facts are far easier to learn and actually use when children understand the structure underneath them, rather than holding 100+ isolated facts in memory with nothing connecting them. Building equal groups or arrays — rows and columns of objects, or a simple grid drawing — makes the structure visible: 6 × 4 is six rows of four, and turning the array on its side shows why 6 × 4 and 4 × 6 give the same answer. Connecting related facts is one of the most efficient ways to build fluency: once 5 × 6 is solid, 6 × 6 is just one more group of six added on, and that relationship is more useful long-term than memorising the two facts separately. Multiplication and division are also two views of the same relationship, so linking them (if 7 × 8 = 56, then 56 ÷ 8 = 7) reinforces both at once. Recall practice — flashcards, quick quizzes, times-table apps — has a place, but it works best sitting on top of this kind of understanding rather than replacing it; drilling a fact a child doesn''t yet understand tends to produce fragile, easily-forgotten memorisation rather than a fact they can rebuild if it slips.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'multiplication-understanding';

UPDATE public.parent_resources
SET body = 'Division can describe two genuinely different real-world actions that happen to use the same operation: sharing a total fairly among a known number of groups (12 lollies between 3 friends — how many each?), or finding how many groups of a given size can be made from a total (12 lollies, 4 per bag — how many bags?). Children who only ever meet one of these — usually sharing — can struggle later when a problem asks the grouping question instead, even though the calculation is identical. Real objects and diagrams make both meanings visible in a way an abstract number sentence doesn''t, and writing the related multiplication fact alongside a division problem (12 ÷ 4 = 3, because 4 × 3 = 12) reinforces that division is the inverse of multiplication rather than a separate, unrelated skill. Remainders deserve real attention rather than being treated as meaningless leftovers: whether a remainder gets rounded up, rounded down, turned into a fraction, or simply reported depends entirely on the context — 13 people needing cars that seat 4 requires 4 cars, not 3.25 of one. Jumping straight to a written algorithm before either meaning is solid tends to produce a procedure children can follow but not really reason about.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'division-understanding';

UPDATE public.parent_resources
SET body = 'Critical reading does not mean distrusting everything a child reads — that would make them harder to teach, not better readers. It means noticing purpose (why was this written?), viewpoint (whose perspective is this?), claims (what is actually being asserted?), evidence (what''s offered to support it?) and, just as importantly, what''s missing. A claim without evidence is worth less confidence than the same claim backed by a specific example, statistic or named source, and part of critical reading is learning to notice the difference automatically rather than accepting confident wording as proof. Comparing two sources on the same topic — even briefly — is one of the most effective ways to build this skill, because it makes gaps and differences visible that are easy to miss when reading only one account: what does each choose to include, leave out, or emphasise? This matters especially for online information, advertisements and persuasive texts, which are often written specifically to sound authoritative regardless of how well-supported the underlying claim actually is. The goal is evaluation, not suspicion — a child who can ask “what would make me more confident about this?” is being critical in the useful sense, while a child taught to distrust everything indiscriminately has learned a much less useful habit.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'critical-reading-for-kids';

UPDATE public.parent_resources
SET body = 'A useful source check asks four things: who created the information, what evidence is provided, whether it''s current enough for the question at hand, and what purpose the source serves — informing, persuading, selling or entertaining are all different jobs, and a source can be genuinely good at one while being poor evidence for a different kind of claim. Credibility is contextual rather than a fixed property of a source: a firsthand account from someone who witnessed an event is strong evidence for what happened, but weak evidence for why it happened scientifically, and a peer-reviewed study is strong evidence for a general pattern but poor evidence for one specific person''s experience. This is a genuinely important distinction for children to build, because the instinct to sort sources into simply “trustworthy” or “not trustworthy” misses that the same source can be excellent for one question and unhelpful for another. A professional-looking website is not automatically reliable, and an amateur or informal-looking one is not automatically unreliable — appearance and design tell you almost nothing about accuracy. Checking who is actually behind the information (an author, an organisation, a clear agenda) and comparing the claim against at least one other credible source are two of the fastest, most reliable checks available, well before formal citation or referencing skills are needed.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'source-credibility-for-kids';

UPDATE public.parent_resources
SET body = 'When children use multiple sources for research, the natural first instinct is usually to summarise Source A, then summarise Source B, then move on — which produces something closer to two book reports stapled together than a genuine synthesis. Real synthesis means organising information by idea rather than by source: what do the sources say about the same specific point, where do they genuinely agree, where does one add something the other doesn''t mention, and where do they actually conflict rather than just phrase things differently? That last distinction matters — two sources reporting slightly different numbers or emphasising different details are not necessarily contradicting each other, and treating every difference as a conflict can make a topic look more contested than it really is. A useful habit is grouping notes by idea before writing anything, rather than working through sources one at a time and hoping the connections emerge naturally in the final piece. It''s also worth remembering that more sources is not automatically better research — a synthesis built from three sources genuinely evaluated for relevance and quality beats one built from six sources skimmed indiscriminately, especially once a child is old enough to be selective about what actually answers their specific question.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'synthesising-sources-at-home';

UPDATE public.parent_resources
SET body = 'From middle primary onward, many unfamiliar words become far easier to work out once children can recognise the meaningful parts inside them: a base word, plus a prefix or suffix that changes or adds to its meaning. “Unhappiness” isn''t one unfamiliar word to memorise — it''s a known base (“happy”) plus two known parts (“un-” meaning not, and “-ness” turning a describing word into a naming word) — and once a child can see that structure, a huge number of related words become accessible through the same base rather than needing to be learned individually. Word families are especially powerful for this reason: one base word such as “act” connects to “action”, “active”, “reaction”, “actor” and “inactive”, and building that family explicitly is more useful than meeting each word as an unrelated item in a different text. It''s worth checking that the predicted meaning actually fits the sentence, though — not every letter string that looks like a prefix or suffix is functioning as one (“re-” in “reading” isn''t the same “re-” as in “redo”), so word-part knowledge works as a strategy to try and verify, not a rule that always applies mechanically. Suffixes in particular also change how a word works grammatically, not just what it means — worth noticing alongside the meaning itself.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'morphology-at-home';

UPDATE public.parent_resources
SET body = 'When an interesting or unfamiliar word comes up — in conversation, a book, a documentary, a hobby — explaining it simply in the moment and connecting it to something your child already knows does more for real vocabulary than any word list. The word needs to be met again in a different context before it properly sticks, so bringing it back up later, even briefly (“remember that word we used for the boat tipping over? capsize”), is worth more than the first explanation on its own. Older children can also start using word parts and surrounding context to work out an unfamiliar word''s meaning independently, which is a transferable strategy rather than a one-off fact. The aim throughout is deep, usable knowledge of words your child will actually encounter again — in their reading, their interests, their conversations — rather than memorising long, disconnected lists of “impressive” words that don''t come up naturally and get forgotten as quickly as they were learned.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'building-vocabulary-at-home';

UPDATE public.parent_resources
SET body = 'A strong paragraph usually needs more than a claim followed by a quotation or an example dropped in and left to speak for itself. Ask your child to state the point clearly first, provide specific evidence that actually supports it, and then explicitly explain how that evidence supports the point — that last step is the one children skip most often, assuming the connection is obvious when it usually isn''t to a reader who doesn''t already know what the writer is thinking. “The character was scared. ''His hands shook.''” leaves the connecting work undone; adding “This shows he was scared because trembling hands are a physical sign of fear” makes the reasoning visible instead of assumed. Older children can push this further by considering a counterargument or a limitation to their own point — acknowledging a case where the claim doesn''t quite hold shows real understanding, not weakness in the argument. Choosing one strong, specific piece of evidence and explaining it properly is worth more than piling in several pieces that are each explained only thinly.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'evidence-paragraphs-at-home';

UPDATE public.parent_resources
SET body = 'Fluency means reading suitable text accurately, with enough automaticity that the reader isn''t spending all their effort decoding individual words, and with phrasing that reflects meaning rather than a flat word-by-word delivery. This matters because reading is genuinely effortful when it''s not yet fluent — a child working hard just to identify each word has very little attention left over for understanding what the sentence actually means, which is why fluency and comprehension are so closely linked. A helpful routine is to read a short section once for accuracy, then reread the same section more smoothly — the second read is where fluency actually develops, because the words are already familiar and attention can shift to phrasing and expression. That expression should come from meaning and punctuation (a question sounds different from a statement, a comma is a small pause) rather than from an adult timing the read or a child racing to finish quickly. Speed genuinely does improve with fluency, but it should be a side effect of accurate, meaningful reading — never the target itself.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'reading-fluency-not-speed';

UPDATE public.parent_resources
SET body = 'Comprehension conversations work best when they match both the text and the child in front of you, rather than following a fixed set of question types. Start with a genuine question you''re actually curious about — not one with an obvious right answer — let your child answer in their own words, then ask what in the text helped them think that. That follow-up matters more than it might seem: it shifts the conversation from “what''s the right answer?” to “how do we know?”, which is the real skill comprehension work is trying to build. As children get older, comprehension can stretch further — comparing ideas across paragraphs or even across sources, and discussing why an author might have made a particular choice (why start the story here? why leave that detail out?) rather than just what happened. One well-chosen question discussed properly, with the child doing most of the talking, teaches more than a long list of shallow ones ticked off quickly. The goal throughout is a real conversation about the text, not a comprehension quiz dressed up as one.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'reading-comprehension-at-home';

UPDATE public.parent_resources
SET body = 'Planning doesn''t need a complicated template to be useful — its job is simply to give a piece of writing somewhere to go before the drafting starts. Naming the purpose (to explain, persuade, entertain), the audience (who''s actually going to read this) and a few main points, then deciding the clearest order for those points, covers most of what a plan needs to do. For a younger writer, that might be as simple as three ideas said aloud and remembered; for an older writer, it might extend to naming what each paragraph is for, which evidence goes where, and a deliberately chosen conclusion rather than the piece just trailing off. It''s worth keeping the plan itself shorter than the eventual piece of writing, and treating it as a rough direction rather than a fixed contract — if drafting reveals a better structure partway through, changing the plan is a sign the writing is actually working, not a failure to stick to the original idea.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'planning-writing-at-home';

UPDATE public.parent_resources
SET body = 'Editing is far more manageable, for both of you, when it has a single clear purpose rather than trying to fix everything at once. One reread might focus purely on clarity — does this sentence say what I mean? Another might focus only on where sentences begin and end, or only on whether the evidence in a paragraph is actually explained, or only on spelling patterns that have already been explicitly taught at school. Older children can take this further, editing specifically for concision (cutting words that aren''t doing any work), cohesion (does one idea lead naturally to the next), or audience (would a reader who doesn''t already know this topic follow it). Trying to correct everything in one pass — spelling, punctuation, structure, word choice, ideas — usually hides the actual learning under a wall of changes, and can leave a child unsure which correction mattered or why. Editing a small section deeply, with one lens at a time, and leaving an already-strong original choice alone, teaches more than a full red-pen pass ever does.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'editing-writing-at-home';

UPDATE public.parent_resources
SET body = 'Shopping, cooking, sport, maps, schedules, building projects and games are all genuinely full of useful, real maths — often more useful than a worksheet, because the numbers mean something and the answer actually matters for what happens next. Questions like “What do you notice?”, “About how much do you think that''ll be?”, “How could we check?” and “Is there another way to work that out?” open up a real conversation rather than a single right-or-wrong answer, and they work at almost any age with the numbers adjusted to suit. The conversation itself is often more valuable than generating lots of written practice questions, because it shows your child that maths is a way of thinking about the world, not a separate subject that only exists on paper. Letting your child estimate first, before calculating exactly, builds a useful sense of whether an answer is even in the right ballpark — a skill that matters well beyond the specific problem in front of them.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'maths-talk-at-home';

UPDATE public.parent_resources
SET body = 'For older readers, the useful shift is moving beyond what a text says to how it says it — noticing that authors make deliberate choices, and that those choices shape how a reader responds. Choose one noticeable element in a short passage: a striking word, an unusually short or long sentence, a heading, a repeated phrase, or where a paragraph breaks — and ask why the author might have chosen it, and what would change with a different choice. Would the sentence “The door slammed” hit differently as “The door closed”? That kind of close, specific comparison is far more useful than a general comment about “descriptive language” or “using techniques”, because it connects a real choice to a real effect a child can actually feel and explain, rather than naming a technique for its own sake. One genuinely close example, discussed properly, teaches more about how writing works than a checklist of literary devices spotted and labelled without asking what any of them actually do for the reader.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'author-choices-at-home';

UPDATE public.parent_resources
SET body = 'For beginning readers, phonics practice at home works best when it reinforces the specific patterns your child has already been taught at school, rather than introducing home-taught shortcuts that may use different terms or a different teaching order. Encourage your child to look all the way through the word rather than guessing from the first letter or the picture, use the letters and sounds they know to sound it out, blend those sounds together, and then reread the whole sentence to check the word actually makes sense in context. That last step matters — a word that''s technically decoded correctly but doesn''t fit the sentence is worth pausing on, because it''s a useful signal to slow down and check rather than push on. It''s worth resisting the urge to teach ahead with a random sequence of advanced patterns your child hasn''t met yet at school; a mismatched sequence can genuinely confuse a beginning reader who''s still working out how the system fits together, even when the intention is to help them get ahead.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'phonics-at-home';

UPDATE public.parent_resources
SET body = 'Reading together should not feel like an oral exam, with a question fired after every page. Talk naturally about whatever is genuinely interesting in the moment — a surprising picture, an unexpected event, a new word, a character doing something silly or brave — the same way you''d talk about a TV show or a story a friend told you. Sometimes pausing to let your child predict what happens next, or retell what''s just happened in their own words, keeps them actively involved with the story rather than passively listening. If your child is learning to read themselves, give them real opportunities to use what they know on some of the words, while protecting the overall meaning and enjoyment of the book — this isn''t the moment for correcting every attempt. Rereading favourite books is genuinely valuable too, not a sign of nothing new happening: a familiar story frees up attention for noticing new details, trying out different voices, or simply enjoying the predictability, all of which build a real, lasting relationship with books.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'shared-reading-without-testing';

UPDATE public.parent_resources
SET body = 'Joining a group that''s already playing is a surprisingly complex social task — reading what the game actually is, finding a natural way in, and coping with a “no” without it feeling like a personal rejection, all at once. Practising a few simple, real phrases in advance gives your child something concrete to reach for in the moment: “Can I join?”, “What can I be?”, or “Can I have a turn when you''re finished?” are all specific enough to actually use, rather than a vague instruction to “go make friends”. It''s worth rehearsing what to do if the answer isn''t an immediate yes too — waiting nearby, asking again in a minute, or choosing something else to do close by are all reasonable next moves, and having practised one in advance makes it much easier to use in the actual moment. The goal is a small, practical toolkit your child can draw on, not a script guaranteed to work every time — even adults get told no when they try to join something, and that''s a normal, survivable part of it too.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'friendship-and-joining-in';

UPDATE public.parent_resources
SET body = 'Early maths is not about worksheets or racing through number facts — at this age, it''s built almost entirely through ordinary moments that already happen in your day. Counting plates as you set the table, comparing two handfuls of blocks to see which has more, sharing food fairly between family members, noticing a repeating pattern in a fence or a piece of clothing, or talking about which container holds more water in the bath all build real mathematical ideas: quantity, comparison, pattern and measurement. Keep the quantities small enough that your child can actually think about what they mean, rather than just reciting a count — knowing that “five” comes after “four” is different from understanding that five actual things is more than four actual things. Asking “How could we check?” before giving the answer yourself, even for something small, builds the habit of reasoning it out rather than simply waiting to be told.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'early-maths-home';

UPDATE public.parent_resources
SET body = 'Names, signs, labels, menus and favourite books are all meaningful, everyday ways for preschool children to notice that print carries a specific message — that those marks on the page aren''t decoration, they say something specific, every time, to anyone who reads them. Point out writing when it has a genuine purpose your child can see: reading a street sign out loud while driving, checking a recipe together, finding their name on a peg or a birthday card. Letting your child make their own marks and labels — even scribbles they call “writing” — builds the same underlying understanding from the other direction, because attempting to write for a purpose is part of how children work out what print is for. Recognition and curiosity about print matter far more at this age than memorising a large set of letters correctly before school starts; formal reading instruction is genuinely the school''s job to begin, not something to race through at home beforehand.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'print-awareness-before-school';

UPDATE public.parent_resources
SET body = 'Strong maths learning comes from genuinely understanding quantities, relationships and strategies — not from moving through calculations quickly. Encouraging drawings, physical objects, number lines and spoken explanations, even for a problem your child could technically answer instantly, keeps that understanding visible and gives you something real to talk about together. Mental fluency does matter and is worth building, but it should grow out of understanding and repeated, low-pressure practice, rather than out of anxiety created by timed tests or a sense that slow means bad at maths. If an answer comes out wrong, asking “How did you think about it?” rather than simply correcting it often reveals exactly where the reasoning went off track, and that''s usually a far more useful next step than just supplying the right answer. It''s also worth noticing when your own instinct is to call one method “the right way” — many valid strategies exist for the same problem, and a child confident enough to explain an unconventional-but-correct approach is showing real understanding, not something to be redirected.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'maths-understanding-not-speed';

UPDATE public.parent_resources
SET body = 'Independence grows through repeated, low-stakes chances to do meaningful things for themselves — opening containers, putting belongings away, getting dressed, packing a bag, or asking an adult for help directly rather than through a parent. These small, real responsibilities matter more than they might seem, because independence is built through practice, not through being told about it or watching someone else do it well. Choose one part of a daily routine your child can genuinely own from start to finish, and gradually reduce your help in that one area rather than trying to hand over everything at once — a narrow, real success builds confidence faster than a broad, wobbly one. It doesn''t need to be fast, and it definitely doesn''t need to be tidy, to count as genuine independence: a lopsided bed made alone is worth more, developmentally, than a perfect one made by an adult while the child watches.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'independence-not-perfection';

UPDATE public.parent_resources
SET body = 'Being ready for school is broader than reading, writing or arithmetic, and it''s worth remembering that formal academic teaching is genuinely the school''s job to begin, not something that needs to already be mostly done at home beforehand. Useful preparation instead focuses on the everyday skills that make the school day itself manageable: managing routines like getting changed for sport or finding their own bag, asking an adult for help directly, participating alongside a group of other children, listening for a reasonably short stretch of time, enjoying stories being read aloud, noticing numbers and quantities in everyday contexts, and being willing to have a go at something new even when it might not work first time. Children arrive at school with genuinely different strengths, and that''s expected and accounted for — school is where the formal teaching of reading, writing and number actually happens, in a planned sequence, rather than something a family needs to have already covered. Practising the practical realities — the actual lunchbox, the actual shoes, a short group routine at home — often does more for a smooth start than any academic head start.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'school-readiness-without-rushing';

UPDATE public.parent_resources
SET body = 'Pretend play, short turn-taking games and toy scenarios give children a genuinely low-pressure way to rehearse social language before they need it for real — trying out the words in a safe, replayable situation rather than only encountering them for the first time in the middle of an actual conflict. You can model how to ask for a turn, ask to join a game already in progress, disagree without a meltdown, repair a mistake (“sorry, I''ll fix it”), or suggest an alternative solution when the first idea doesn''t work for everyone. Because some of that language is already familiar from play, real conflicts become easier to navigate when they do arise — the child has something to reach for instead of only big feelings and no words. Praising the strategy itself (“good idea, offering to swap”) rather than a vague “good sharing” also helps a child notice which specific move actually worked, so they''re more likely to try it again next time.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'social-learning-through-play';

UPDATE public.parent_resources
SET body = 'At home, the most useful writing support often happens before and after the actual drafting, rather than during it. Before writing, help your child say the idea out loud first, or organise a few points into a rough order — talking an idea through often reveals what''s actually being said, and where the gaps are, well before a single sentence is written. After a draft exists, ask what the reader would need to know to understand it, and help your child reread one specific sentence for clarity rather than the whole piece at once. It''s worth actively avoiding dictating polished sentences for your child to simply copy down — it''s tempting when a piece is due and time is short, but it teaches that the “real” sentence comes from an adult, not from them. The writing that comes out the other end should still genuinely sound like your child, even in the places where you''ve clearly helped them think something through more carefully.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'help-with-writing-at-home';

UPDATE public.parent_resources
SET body = 'Early writers are juggling several genuinely hard things at once — holding onto an idea, breaking words into sounds, remembering which letters represent those sounds, leaving spaces between words, and controlling a pencil — all at the same time, which is a significant amount of simultaneous effort for a beginner. Letting them get the message down first, using whatever spelling and letter knowledge they currently have, protects that effort and keeps the actual purpose of writing — saying something to someone — at the centre of the experience. Afterwards, it''s worth choosing just one small, specific teaching point to focus on, if there''s a genuine reason to, rather than working through every possible correction on the page. A page returned covered in adult corrections can quickly teach a child that writing is mainly about avoiding mistakes, rather than about having something worth saying — which is a difficult lesson to undo later, even once the mechanical skills have caught up.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'early-writing-without-correcting-everything';

UPDATE public.parent_resources
SET body = 'Children manage feelings more effectively once they can begin to notice and name what''s actually happening inside them, rather than experiencing a big feeling as an overwhelming, unlabelled wave. Talk about feelings when everyone involved is calm — not in the middle of a meltdown — and connect the feeling word to a physical body clue your child can actually notice next time: a hot face, clenched fists, a fast heartbeat. Practising one or two simple, genuinely calming strategies during these quiet moments (slow breaths, a squeeze toy, counting something) means your child has already rehearsed the strategy before they need it under pressure, which matters because almost nothing new can be learned in the middle of real distress. During an actual big moment, use fewer words rather than more, and help your child return to a calmer state first — the problem-solving conversation genuinely works better afterward, once the feeling itself has passed.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'talking-about-big-feelings';

UPDATE public.parent_resources
SET body = 'When a task is hard, the most useful help is often a smaller prompt rather than handing over the solution outright — the goal is to keep your child thinking, not to get the task finished faster. Asking what they''ve already tried, pointing to one specific part worth a second look, offering two possible next moves to choose between, or making the task itself slightly easier are all ways to keep your child in the driver''s seat while still making progress reachable. This matters because a child who''s shown the answer immediately learns that getting stuck means an adult takes over, while a child given a genuine next step learns that getting stuck is a normal, solvable part of the process. It''s worth resisting both extremes here — jumping in with the answer too fast, and withholding all help in the name of “building resilience” when a child is genuinely stuck and getting nowhere. A small, well-timed prompt usually does more for real learning than either.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'help-without-taking-over';

UPDATE public.parent_resources
SET body = 'Young children learn a huge amount from conversation that follows their own attention, rather than from conversation an adult has decided to direct. Comment on what your child is doing or interested in right now, wait a moment, then add a little more language onto what they''ve already said — if they say “big truck”, you might add “yes, a big yellow truck, it''s going fast!” You don''t need to quiz them about it or ask them to repeat a perfect sentence back; the goal is a warm, genuine back-and-forth exchange where both people are actually contributing something, not a one-sided language lesson disguised as a chat. Rapid-fire questions can actually shut this kind of exchange down rather than encourage it, because they turn a conversation into something closer to an interview. A few unhurried seconds of wait time after your child speaks, giving them room to add more if they want to, often does more for real language growth than any number of extra questions.',
    content_version = 'resource-v1.1',
    updated_at = now()
WHERE id = 'early-years-talk';
