-- m30 (30-35 months) activity expansion: 4 -> 28 active activities.
-- Same 9-area taxonomy as the m24 expansion. Shows genuine developmental
-- progression beyond m24 (3-word sentences, 3-step sequences, joining
-- others' play, more independence) rather than repeating m24 mechanics.
-- Guardrail-checked against development_stages.content_guardrails for m30;
-- no violations. skill_key left null (pathways start at m36).
-- Duplicate-title-checked against live titles before insert (1 title
-- collision found and renamed: 'Tell me what happened' already exists on
-- a different m36 activity with different content).

INSERT INTO public.weekly_activities
  (id, stage_key, area, title, activity_template, why_it_matters, easier_variant, stretch_variant, curriculum_map, source_basis, content_version, sort_order, active, resource_keys)
VALUES
  (
    'm30-three-word-sentences',
    'm30',
    'Communication',
    'Model a three-word sentence',
    'When {name} uses two words together, respond with a natural three-word version that adds one more piece — “more banana” becomes “want more banana”.',
    'Modelling a slightly longer sentence, without asking for a repeat, is how phrase length grows at this age.',
    'Accept the two-word version and simply model the three-word one back.',
    'Model a four-word sentence when {name} is ready.',
    '{"Victoria": "VEYLDF Outcome 5 — children are effective communicators", "Queensland": "EYLF V2.0 Outcome 5 — children are effective communicators", "New Zealand": "Te Whāriki — Mana Reo / Communication", "New South Wales": "EYLF V2.0 Outcome 5 — children are effective communicators"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    65,
    true,
    ARRAY['two-word-phrases-and-beyond']::text[]
  ),
  (
    'm30-wh-question',
    'm30',
    'Communication',
    'Ask one simple “where” or “what” question',
    'During play, ask one simple question such as “where''s the dog?” or “what''s that?” about something genuinely in view, and wait for any kind of answer.',
    'Answering simple wh-questions is a key language step that builds on understanding single instructions.',
    'Answer the question yourself first as a model, then ask again.',
    'Ask a “why” or “how” question about something familiar.',
    '{"Victoria": "VEYLDF Outcome 5 — children are effective communicators", "Queensland": "EYLF V2.0 Outcome 5 — children are effective communicators", "New Zealand": "Te Whāriki — Mana Reo / Communication", "New South Wales": "EYLF V2.0 Outcome 5 — children are effective communicators"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    66,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-i-and-you',
    'm30',
    'Communication',
    'Practise “I” and “you” in play',
    'During pretend play or a simple game, use “I” and “you” clearly and often — “I''m hiding, you find me” — and notice if {name} starts using them too.',
    'Pronouns are tricky at this age because they change depending on who''s speaking; hearing them used clearly and often helps them click.',
    'Use names instead of pronouns for now, alongside the pronoun.',
    'Gently expand if {name} mixes up “me” and “I” rather than correcting directly.',
    '{"Victoria": "VEYLDF Outcome 5 — children are effective communicators", "Queensland": "EYLF V2.0 Outcome 5 — children are effective communicators", "New Zealand": "Te Whāriki — Mana Reo / Communication", "New South Wales": "EYLF V2.0 Outcome 5 — children are effective communicators"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    67,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-three-piece-puzzle',
    'm30',
    'Thinking',
    'A puzzle with a few more pieces',
    'Offer a simple four- or five-piece puzzle, a step up from a two-piece one, and let {name} work out where each piece goes.',
    'A few more pieces adds real challenge to the same trial-and-adjustment thinking, without becoming frustrating.',
    'Turn one tricky piece to the right position and let {name} finish it.',
    'Time how long it takes and try again to beat that time together, just for fun.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    68,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-three-step-sequence',
    'm30',
    'Thinking',
    'Copy my three steps',
    'Do a short three-step action with toys, such as stacking a block, adding a second, then adding a small figure on top, and invite {name} to copy the whole sequence.',
    'Holding and repeating a three-step sequence is a genuine step up in memory and planning from a two-step one.',
    'Break it into two steps first, then add the third once that''s easy.',
    'Add a fourth step to the sequence.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    69,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-jump-both-feet',
    'm30',
    'Movement',
    'Jump with both feet together',
    'On a soft, safe surface, encourage {name} to practise jumping with both feet leaving the ground at the same time, landing however they can.',
    'Jumping with both feet together is a genuine new gross-motor skill typically emerging around this age.',
    'Hold both of {name}''s hands for balance while they practise.',
    'Jump over a very low, soft object like a folded towel.',
    '{"Victoria": "VEYLDF Outcome 3 — children have a strong sense of wellbeing", "Queensland": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing", "New Zealand": "Te Whāriki — Mana Atua / Wellbeing", "New South Wales": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    70,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-stairs-with-rail',
    'm30',
    'Movement',
    'Stairs with a rail',
    'On a safe, supervised staircase, let {name} practise going up holding the rail, placing both feet on each step before moving to the next.',
    'Managing stairs with support builds balance, strength and confidence for climbing more independently later.',
    'Hold {name}''s free hand as well as the rail.',
    'Practise coming back down the stairs the same careful way.',
    '{"Victoria": "VEYLDF Outcome 3 — children have a strong sense of wellbeing", "Queensland": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing", "New Zealand": "Te Whāriki — Mana Atua / Wellbeing", "New South Wales": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    71,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-six-block-tower',
    'm30',
    'Fine motor',
    'Build a taller tower',
    'Offer blocks and see how many {name} can stack — aim together for around six blocks, celebrating the attempt whether or not it topples.',
    'Stacking around six blocks is a fine-motor and patience milestone typical of this age.',
    'Start with three or four blocks and build up gradually.',
    'Try building on an uneven surface like a cushion for extra challenge.',
    '{"Victoria": "VEYLDF Outcome 3 — children have a strong sense of wellbeing", "Queensland": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing", "New Zealand": "Te Whāriki — Mana Atua / Wellbeing", "New South Wales": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    72,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-twist-open-lid',
    'm30',
    'Fine motor',
    'Twist and open',
    'Offer a few safe, child-sized screw-top containers or large knobs and let {name} practise twisting them open and closed.',
    'Twisting motions use a different hand and wrist action from grasping, and this is a genuine new skill around this age.',
    'Loosen the lid first so only a small twist is needed to finish.',
    'Offer a container with a slightly stiffer lid.',
    '{"Victoria": "VEYLDF Outcome 3 — children have a strong sense of wellbeing", "Queensland": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing", "New Zealand": "Te Whāriki — Mana Atua / Wellbeing", "New South Wales": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    73,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-safety-scissor-snip',
    'm30',
    'Fine motor',
    'First snips with safety scissors',
    'With close supervision, let {name} practise one or two snips into the edge of a strip of paper using child-safe, blunt-tipped scissors.',
    'A first supervised experience with scissors builds the two-handed coordination that formal cutting skills build on later.',
    'Hold the paper taut for {name} so the scissors have something firm to bite into.',
    'Try snipping along a thick drawn line.',
    '{"Victoria": "VEYLDF Outcome 3 — children have a strong sense of wellbeing", "Queensland": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing", "New Zealand": "Te Whāriki — Mana Atua / Wellbeing", "New South Wales": "EYLF V2.0 Outcome 3 — children have a strong sense of wellbeing"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    74,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-wash-and-dry-hands',
    'm30',
    'Independence',
    'Wash and dry hands mostly alone',
    'At a step stool and sink, let {name} attempt each step of hand washing themselves — wetting, soap, rubbing, rinsing, drying — with help only where needed.',
    'A multi-step routine like hand washing builds sequencing and independence together.',
    'Do the soap and rubbing step together, and let {name} manage the rest.',
    'See how much of the whole sequence {name} can do without a reminder.',
    '{"Victoria": "VEYLDF Outcome 1 — children have a strong sense of identity", "Queensland": "EYLF V2.0 Outcome 1 — children have a strong sense of identity", "New Zealand": "Te Whāriki — Mana Whenua / Belonging", "New South Wales": "EYLF V2.0 Outcome 1 — children have a strong sense of identity"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    75,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-choose-and-start-dressing',
    'm30',
    'Independence',
    'Choose and start getting dressed',
    'Offer a choice between two simple outfits, then let {name} attempt to start putting on the chosen item themselves before helping.',
    'Making the choice and attempting the first step builds both decision-making and dressing independence.',
    'Lay the clothing out in the order it goes on to make the sequence clearer.',
    'Let {name} attempt a second item before any help is offered.',
    '{"Victoria": "VEYLDF Outcome 1 — children have a strong sense of identity", "Queensland": "EYLF V2.0 Outcome 1 — children have a strong sense of identity", "New Zealand": "Te Whāriki — Mana Whenua / Belonging", "New South Wales": "EYLF V2.0 Outcome 1 — children have a strong sense of identity"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    76,
    true,
    ARRAY['me-do-it-toddler-independence']::text[]
  ),
  (
    'm30-pour-own-drink',
    'm30',
    'Independence',
    'Pour your own drink',
    'With a small, light jug of water or milk, let {name} practise pouring their own drink into a cup, expecting some spills.',
    'Pouring a real drink independently builds fine motor control and everyday self-reliance.',
    'Use a jug that''s only a quarter full to reduce spills.',
    'Let {name} pour a second cup for someone else at the table.',
    '{"Victoria": "VEYLDF Outcome 1 — children have a strong sense of identity", "Queensland": "EYLF V2.0 Outcome 1 — children have a strong sense of identity", "New Zealand": "Te Whāriki — Mana Whenua / Belonging", "New South Wales": "EYLF V2.0 Outcome 1 — children have a strong sense of identity"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    77,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-join-the-game',
    'm30',
    'Play',
    'Join a game already happening',
    'If another child is already playing nearby, support {name} to approach and join with a simple action or phrase, like picking up a matching toy and joining in.',
    'Joining play already in progress is a harder social skill than parallel play, and this age is when interest in it typically grows.',
    'Join alongside {name} the first few times to model how to approach.',
    'Let {name} choose their own way to ask or join in.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    78,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-two-step-pretend',
    'm30',
    'Play',
    'A pretend story with two steps',
    'Extend a pretend routine into two linked actions, such as feeding a teddy and then putting it to bed, rather than just one action on its own.',
    'Linking two pretend actions into a small sequence is a real step up in imaginative and narrative thinking.',
    'Do the first action together, then pause and ask “what happens next?”',
    'Add a third linked action to the pretend sequence.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    79,
    true,
    ARRAY['early-pretend-play-onset']::text[]
  ),
  (
    'm30-be-the-doctor',
    'm30',
    'Play',
    'Take on a simple role',
    'Offer a simple role to play, such as “doctor” checking a teddy''s heartbeat with a toy stethoscope, and follow {name}''s lead on what happens.',
    'Taking on a simple role and acting from inside it is a more advanced form of pretend play than acting on a single toy.',
    'Play the role together, taking turns being the doctor.',
    'Add a second role, like a patient with a different problem.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    80,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-retell-in-your-words',
    'm30',
    'Early literacy',
    'Retell the story your way',
    'After reading a short, familiar story, ask {name} to tell you what happened in their own words, accepting any version they give.',
    'Retelling a story, even loosely, builds the narrative memory and sequencing that supports comprehension later.',
    'Ask about just the very last part of the story.',
    'Ask {name} what they think happens next, beyond the book.',
    '{"Victoria": "VEYLDF Outcome 5 — children are effective communicators", "Queensland": "EYLF V2.0 Outcome 5 — children are effective communicators", "New Zealand": "Te Whāriki — Mana Reo / Communication", "New South Wales": "EYLF V2.0 Outcome 5 — children are effective communicators"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    81,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-notice-the-rhyme',
    'm30',
    'Early literacy',
    'Notice two words that rhyme',
    'In a rhyming book or song, pause on two rhyming words and say them slowly, noticing out loud that they sound alike at the end.',
    'Noticing rhyme is an early, playful step toward hearing the sounds inside words.',
    'Just point out the rhyme yourself without asking {name} to notice it.',
    'Ask {name} to think of another word that sounds the same.',
    '{"Victoria": "VEYLDF Outcome 5 — children are effective communicators", "Queensland": "EYLF V2.0 Outcome 5 — children are effective communicators", "New Zealand": "Te Whāriki — Mana Reo / Communication", "New South Wales": "EYLF V2.0 Outcome 5 — children are effective communicators"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    82,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-make-a-card',
    'm30',
    'Early literacy',
    'Make a card for someone',
    'Offer paper and crayons and encourage {name} to make a card with scribbles or marks for someone they know, then “deliver” it together.',
    'Making a card for a real person gives mark-making a genuine purpose, which is motivating at this age.',
    'Start the card together and let {name} add their own marks.',
    'Ask {name} to “tell” you what the card says as if reading it back.',
    '{"Victoria": "VEYLDF Outcome 5 — children are effective communicators", "Queensland": "EYLF V2.0 Outcome 5 — children are effective communicators", "New Zealand": "Te Whāriki — Mana Reo / Communication", "New South Wales": "EYLF V2.0 Outcome 5 — children are effective communicators"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    83,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-count-a-small-set',
    'm30',
    'Early numeracy',
    'Count a small group of things',
    'Count a small group of real objects together — up to four or five — pointing to each one as you say the number.',
    'Touching one object per number word is the foundation of accurate counting, more important right now than counting fast.',
    'Count just two or three objects.',
    'Ask “how many were there?” right after counting to see if the last number sticks.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    84,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-more-or-less',
    'm30',
    'Early numeracy',
    'Which group has more?',
    'Set out two small, uneven groups of the same object and ask {name} which group has more, without counting first.',
    'Judging more and less by eye is an early number sense skill that comes before formal counting comparison.',
    'Make the difference between groups very obvious.',
    'Count both groups afterward to check the guess.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    85,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-simple-pattern',
    'm30',
    'Early numeracy',
    'Continue a simple pattern',
    'Make a simple repeating pattern with two colours or objects, such as red-blue-red-blue, and ask {name} what comes next.',
    'Continuing a simple pattern is genuine early maths reasoning, separate from counting.',
    'Make the pattern with just three items and ask for one more.',
    'Try a pattern with three repeating items instead of two.',
    '{"Victoria": "VEYLDF Outcome 4 — children are confident and involved learners", "Queensland": "EYLF V2.0 Outcome 4 — children are confident and involved learners", "New Zealand": "Te Whāriki — Mana Aotūroa / Exploration", "New South Wales": "EYLF V2.0 Outcome 4 — children are confident and involved learners"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    86,
    true,
    ARRAY[]::text[]
  ),
  (
    'm30-name-your-feeling',
    'm30',
    'Connection',
    'Say how you feel',
    'When {name} shows a clear feeling, offer the word for it and invite them to say it too: “you''re frustrated — can you say ‘I''m frustrated’?”',
    'Being offered the actual word for a feeling, and trying it out, builds emotional vocabulary this age is ready to use.',
    'Just offer the word without asking {name} to repeat it.',
    'Ask {name} to say what might help them feel better.',
    '{"Victoria": "VEYLDF Outcome 2 — children are connected with and contribute to their world", "Queensland": "EYLF V2.0 Outcome 2 — children are connected with and contribute to their world", "New Zealand": "Te Whāriki — Mana Tangata / Contribution", "New South Wales": "EYLF V2.0 Outcome 2 — children are connected with and contribute to their world"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    87,
    true,
    ARRAY['toddler-tantrums-before-three']::text[]
  ),
  (
    'm30-comfort-a-friend',
    'm30',
    'Connection',
    'Help a sad toy feel better',
    'Set up a small scenario where a toy or teddy is “sad”, and invite {name} to think of a way to help it feel better, like a hug or a kind word.',
    'Practising comfort on a toy builds the same empathic response that later gets used with real people.',
    'Model the comforting action first, then let {name} try.',
    'Ask {name} why they think the toy felt sad in the first place.',
    '{"Victoria": "VEYLDF Outcome 2 — children are connected with and contribute to their world", "Queensland": "EYLF V2.0 Outcome 2 — children are connected with and contribute to their world", "New Zealand": "Te Whāriki — Mana Tangata / Contribution", "New South Wales": "EYLF V2.0 Outcome 2 — children are connected with and contribute to their world"}'::jsonb,
    'Learn Along original activity informed by age-stage developmental guidance',
    'activity-v5.0',
    88,
    true,
    ARRAY[]::text[]
  )
;
